### ISSUE TITLE
Error in parsing strings with )

### ISSUE THREAD

**Issue by mistermjtek** [sindresorhus/get-urls#16]
When parsing the string "[Lorem Ipsum](http://stream4us.info/stream/stream.html)", the URL that returns is "http://stream4us.info/stream/stream.html)"

The extra ) character on the end shouldn't be included in the URL, I'm assuming. How do we handle this?

**Comment by noffle** [comment]
This is likely an issue with the underlying module, [url-regex](https://github.com/kevva/url-regex). You may need to file a bug there instead.

**Comment by sindresorhus** [comment]
⬆️ 👍

**Comment by skyebook** [comment]
FWIW, @mistermjtek, I've made a pull request to fix this issue here: https://github.com/kevva/url-regex/pull/35
