### ISSUE TITLE
es6 in index.js breaks build in create-react-app

### ISSUE THREAD

**Issue by barbalex** [sindresorhus/get-urls#17]
in this commit: https://github.com/sindresorhus/get-urls/commit/c80aa4501014bc4d0e95bfb8f811736be6975ad7

using an arrow function in index.js was introduced.

My project uses [create-react-app](https://github.com/facebookincubator/create-react-app). When building for production, I get an almost identical error to what is mentioned for example here: https://github.com/facebookincubator/create-react-app/issues/984:

    > react-scripts build && sw-precache --config=sw-precache-config.js

    Creating an optimized production build...
    Failed to compile.

    static/js/main.6e4ce89f.js from UglifyJs
    SyntaxError: Unexpected token: operator (>) [./~/get-urls/index.js:5,0]

According to [this comment](https://github.com/facebookincubator/create-react-app/issues/984#issuecomment-257105773) the reason for the issue is that uglify can not deal with es6 and create-react-app uses uglify.

It may have been a little early to es6-ify a tool like get-urls that is used by many people when other important tools in the ecosystem like uglify can not (yet) deal with es6.

But I do see that once users have found out what is going on, there is a fairly easy solution: use an old version of get-urls.

So don't hesitate to close this issue. But maybe warn users in the readme?

Anyway: thanks for this great tool :-)

**Comment by SamVerschueren** [comment]
You can still use `5.0.1` if you want. More information regarding this topic https://github.com/sindresorhus/ama/issues/446#issuecomment-281014491.

**Comment by barbalex** [comment]
Yep. Additionally it seems like create-react-app will soon change from uglify to babili so I don't have to indefinitely remain on an old version :-)

By the way, @SamVerschueren: Thanks a lot from reducing the burden from @sindresorhus and hopfully enabling him to remain crazy productive!

**Comment by SamVerschueren** [comment]
> Thanks a lot from reducing the burden from @sindresorhus and hopefully enabling him to remain crazy productive! 

Thanks, try to help wherever I can ;)
