### ISSUE TITLE
I got Error with Uglify

### ISSUE THREAD

**Issue by muhajirframe** [sindresorhus/get-urls#20]
Hi, i am sorry if i post issue on wrong repository.

Inlcude this package in my `next.js` project.
It works find with development mode. But when i build it, i got this error. I also got the same kind of error with `nuxt.js`
```javascript
> Failed to build on /tmp/89b841dc-5001-49e5-9048-d57b1b2de376
{ Error: commons.js from UglifyJs
```

Is there any workaround for this please?

**Comment by sindresorhus** [comment]
You want the ES2015 compatible version of Uglify: https://www.npmjs.com/package/uglify-es Or you need to use Babel on your dependencies, see https://github.com/sindresorhus/ama/issues/446 and https://github.com/SamVerschueren/babel-engine-plugin
