### ISSUE TITLE
Unhandled rejection URIError: URI malformed

### ISSUE THREAD

**Issue by bonustrack** [sindresorhus/get-urls#22]
I found an url that make `get-urls` throw an error
```
Unhandled rejection URIError: URI malformed
```

To reproduce the issue, parse this string with `get-urls`:
```
Hello http://example.com/D%C9PLIANT World
```

`%C9` is used to create an accent in french.

**Comment by sindresorhus** [comment]
It's coming from https://github.com/sindresorhus/normalize-url/blob/48b1864f8ef197df46abc380f55ca6f831d52fed/index.js#L84

This seems relevant: https://stackoverflow.com/questions/9064536/javascript-decodeuricomponent-malformed-uri-exception

This works, but I don't think that's a good solution:

```js
decodeURI(unescape('http://example.com/D%C9PLIANT'))
```

**Comment by MortenHofft** [comment]
Thank you for a nice library.

```
var getUrls = require("get-urls");
var str = "https://a.bc/%";
getUrls(str); //fails
getUrls(decodeURI(unescape(str))); //fails as well
```

I would expect either no results if the url is indeed malformed

**Comment by sindresorhus** [comment]
This was fixed by https://github.com/sindresorhus/get-urls/commit/d3d0f2914590407416566a715b7349d4890c1da7
