### ISSUE TITLE
create react app build fails during minification

### ISSUE THREAD

**Issue by CaryLandholt** [sindresorhus/get-urls#23]
The package works as expected in development but fails during the [create react app](http://bit.ly/2tRViJ9) build's minification phase.

![image](https://user-images.githubusercontent.com/833972/31480045-11a91598-aee1-11e7-8d90-0887ed10c4bc.png)

The link suggests the following:
> Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled (retaining ES6 Modules).

Specifically, minification is failing on the fatarrows.
Would you accept a PR to address?

**Comment by CaryLandholt** [comment]
btw - this is also the case for any dependencies of `get-urls` package, including `url-regex`

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
