### ISSUE TITLE
unescaping html codes is not sufficient

### ISSUE THREAD

**Issue by regevbr** [sindresorhus/get-urls#28]
Currently the code uses escape-goat which doesnt handle all asci codes.
A better library would be [https://github.com/mdevils/node-html-entities] which parses all codes such as `&#43;` which translates to +

**Comment by regevbr** [comment]
@sindresorhus what do you say?

**Comment by sindresorhus** [comment]
Thinking about this some more I don’t think it makes sense for this module to unescape at all. It accepts a string. It should be up to the user to know how to properly pass in a valid string.

**Comment by regevbr** [comment]
I think the point is to make it easier for the user. Maybe we can add ia as
an optional feature?

On Dec 3, 2017 00:08, "Sindre Sorhus" <notifications@github.com> wrote:

Thinking about this some more I don’t think it makes sense for this module
to unescape at all. It accepts a string. It should be up to the user to
know how to properly pass in a valid string.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sindresorhus/get-urls/issues/28#issuecomment-348723730>,
or mute the thread

**Comment by sindresorhus** [comment]
You want HTML unescaping. Someone else might something different. I don't want to be opinionated about where the text is from. If you have to set an option you could just as easily run the unescape module. And you could always make a wrapper module called `get-urls-from-html` which does the decoding.

**Comment by regevbr** [comment]
so why do you normalize the urls? let the user decide if he wants to do that...
