### ISSUE TITLE
Issue with minifying in create-react-app for production build

### ISSUE THREAD

**Issue by amalajith** [sindresorhus/get-urls#30]
Unable to minify the code.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
