### ISSUE TITLE
Keep Unnormalized

### ISSUE THREAD

**Issue by rwieruch** [sindresorhus/get-urls#32]
Hey @sindresorhus I have found out about all your URL npm packages. Thanks for providing them!

I have an issue though that cannot be fulfilled by the library. I have a case where I want to keep the URLs unnormalized to replace those findings later on in a string. I couldn't find any option to not normalize the url entirely, even though I passed in all options for https://github.com/sindresorhus/normalize-url  as false. 

I had something in mind [like this](https://github.com/rwieruch/get-urls/commit/bc755bc9110dd0f51f5ba2b7ed8c8f2072c8bbb0). Maybe it should go one layer deeper into [normalize-url](https://github.com/sindresorhus/normalize-url) by exposing **all** options for normalizing the URL. That way, a library user would be able to pass in all options as false to keep the URL unnormalized.

Perhaps I use the wrong library in the first place for my use case, but I couldn't find any other for dealing with it. Thanks again for providing it!

**Comment by sindresorhus** [comment]
Would be better to just use https://github.com/kevva/url-regex with `String#replace()`.
