### ISSUE TITLE
www is stripped from url.

### ISSUE THREAD

**Issue by entrptaher** [sindresorhus/get-urls#33]
If the provided list has www, then it removes the www part, it's crucial for some websites.

![image](https://user-images.githubusercontent.com/8284972/34299460-3e2f13e8-e74d-11e7-8f8c-92f62212d32d.png)

For example: 
This url loads: https://www.stateofthedapps.com/dapps/etherpoly
This url doesn't load: https://stateofthedapps.com/dapps/etherpoly

So if the www is removed for no reason, then the final Set has invalid links.

**Comment by studioraygun** [comment]
You can pass in an option to not strip the www:
https://github.com/sindresorhus/normalize-url#stripwww
