### ISSUE TITLE
This module is not working for some cases

### ISSUE THREAD

**Issue by shahidmau** [sindresorhus/get-urls#34]
I am trying to pass below contents into the function but no response is coming. Kindly check.

> var getUrls = require( 'get-urls' );
> 
> 
> var post_content = '原标题：陕西南郑除夕凶案：一男子连杀邻家父子三人，两天后自首　　除夕（2月15日）中午，陕西汉中南郑区男子张扣扣“犯了捅天的娄子”：他持刀将邻居王自新及其两个儿子王校军、王正军，先后杀害。案发后警方在周边地区张贴的协查通报　　2月19日下午，张扣扣的四伯张宏儒向澎湃新闻（www.thepaper.cn）表示，事发后他曾试图劝说张扣扣，但被他甩开，“他说22年的大仇报了。”　　张扣扣所说的“大仇”，记载在一份判决书上：南郑法院认定，1996年8月27日，张扣扣的母亲汪秀萍因琐事与王正军等人发生冲突，在冲突中，王正军用一根木棒猛击汪秀萍的头部，汪秀萍当晚身亡。当年12月5日，南郑法院一审认定时年17岁的王正军犯故意伤害（致人死亡）罪，判处有期徒刑7年，由其监护人王自新一次性赔偿张福如经济损失9639.3元。　　这份判决下达22年后，年已35岁的张扣扣，持刀杀害王自新父子三人。大年初二（2月17日）上午，张扣扣投案自首。　　对于一些网络文章将张扣扣称为“英雄”的说法，有村民表示不满，“杀人能是英雄？简直是胡说八道！”　　汉中市公安局南郑区分局一位值班警官表示，此案正在侦办。　　除夕凶案　　除夕当天扫墓祭祖，是许多地区的传统习俗，陕西汉中地区亦不例外。2月15日是除夕，早饭过后，汉中南郑区新集镇王坪村14组的张福如和他大哥、二哥，以及四弟家的儿子一同去后山祭拜祖先。　　上午9时许，张福如随身背了一个背篓，装着砍柴的工具，以及纸钱、香烛、鞭炮等上山祭祖。“我出门的时候我儿子（张扣扣）在洗棉袄。”张福如说，父子两人当时并无言语交流。众人祭祖还没完，“我侄子就给我说，你赶紧往回走，越快越好。”张福如说，侄子接到一个电话，说出事了，让他赶快回家。　　往山下走了不远，张福如听见村里有警报声，又远远看见一个人向他跑来，“看样子是要截我”，张福如隐约感觉不妙，扭头又上了山，躲进后山老屋，直到初一晚上七点左右才下山。在村委会里，张福如听说儿子杀人了，“我浑身都软了。”　　据王坪村14组多名村民介绍，除夕中午，张扣扣拿着一把二三十公分长的尖刀，先后将王自新及其大儿子王校军、三儿子王正军杀害——王家兄弟当时也是刚刚祭祖归来。案发现场　　王自新家邻居张洪亮（化名）说：“扣扣杀人的时候我儿媳妇带着孩子在门口玩，把她都吓哭了。扣扣戴着口罩和帽子，大家没认出来，还以为是个疯子。后来他回家取油烧车，出来的时候摘了口罩帽子，大家才认出杀人的是扣扣。”　　据与王自新家一路之隔的村民张辉（化名）描述，犯案之后，张扣扣又回家拿了两瓶油，一瓶扔进到王校军轿车车厢里，一瓶砸在轿车后挡风玻璃上，并将油点燃。张辉称，“他（王校军）的车就在我家门口停着，火苗子都溅到我的车上了。”邻里众人赶紧将火扑灭。　　“我当时还劝他（张扣扣）不要搞事情，他说他杀了三个人，这回死定了。”张辉说，张扣扣当时不仅持有一把尖刀，还拿着一把手枪，“是真枪还是假枪就不知道了，反正他也没开枪。”　　张扣扣家左邻是他的四叔张宏儒家，事发时，张宏儒正在家杀鸡，一个晚辈跑进来说：“出大事了。”张宏儒出去到路上才知道是张扣扣杀人了，张宏儒说：“我赶紧拉他一把，说你咋弄这么大事。”　　“扣扣一下把我甩开，说他把22年的仇报了。”张宏儒说，“刀在他口袋里装着。”张宏儒心生恐惧，没再敢拦张扣扣，眼看着他出村子逃走了。　　据村民介绍，张、王两家在穿村而过的道路同侧，两家院子一前一后中间夹着王自新兄弟的房子。张扣扣家为一幢二层小楼，受害人王自新家则是略显破败的一幢平房。王家平常只有老两口在家，三个儿子均在外上班，“他们在城里买了房，所以也没修家里的屋子。”张福如称，他家的二层楼是他在2007年和2013年分两次才修起来，花了十几万元。　　2月20日，王自新的一名侄子对澎湃新闻说，关于22年前的案子，网上流传的判决书写得很清楚，那是法院查明的事实。　　22年前的命案　　22年前血案的涉事双方，正是张福如、王自新两家。　　张福如称，两家矛盾源于他家“给别的人送了一颗西瓜，没有给王家送”而引发。而包括张福如本家亲戚在内的多名村民向澎湃新闻表示，张福如的妻子汪秀萍为人强势，“嘴上不饶人”，“和村里很多人都吵过架”。在王坪村担任二十多年村干部的王明亮（化名）也表示，汪秀萍个性不好。　　张扣扣父亲张福如提供的“（1996）南刑初字第142号”刑事附带民事判决书认定，张福如之妻汪秀萍过往与被告人王正军之母杨桂英关系不睦。1996年8月27日19时，汪秀萍路过被告人王正军家门前时，给王正军二哥王富军脸上吐唾沫，引起争吵后被告人王正军闻讯赶到现场，也同汪秀萍争吵并厮打。汪秀萍遂拿一节扁铁在被告人王正军的左额部及左脸部各打一下，王正军即捡起一木棒朝汪秀萍头部猛击一棒，致汪倒地后于当晚22时许死亡。经法医鉴定：死者汪秀萍系钝性外力所致颅脑损伤而死亡。　　案发后，被告人王正军之父王自新代为办理汪秀萍丧葬共花费8139.3元。附带民事诉讼原告人张福如也为汪秀萍丧葬事宜垫付现金及实物折款共1100余元。庭审中，张福如最后要求被告人王正军给其赔偿经济损失24万元人民币。被告人王正军及其监护人王自新均表示，其家庭经济困难，无力赔偿。　　法院查明，被告人王正军家庭困难属实，经当庭调解，对附带民事赔偿问题未达成协议。南郑法院认为，被告人王正军所犯故意伤害（致人死亡）罪事实存在，罪名成立。由于被告人王正军的犯罪行为给附带民事诉讼原告人张福如造成的经济损失应予赔偿。但鉴于被告人王正军系在校学生，又未成年（1979年4月23日出生，时年17岁），且家庭经济困难属实，现确无力全额赔偿，故可酌情予以赔偿。鉴于被告人王正军在犯罪时尚未满18周岁，且能坦白认罪，其父已代为支付死者巨额丧葬费用，加之被害人汪秀萍对引发本案在起因上有一定过错责任，应对被告人王正军从轻处罚。　　最终，南郑法院一审判决王正军犯故意伤害（致人死亡）罪，判处有期徒刑七年；由被告人王正军的监护人王自新一次性偿付附带民事诉讼原告人张福如经济损失9639.3元（除王自新已支付汪秀萍丧葬费8139.3元外，其余1500元限王自新在本判决生效后十日内付清）。　　2月19日晚，张福如告诉澎湃新闻，他实际拿到手的现金赔偿只有1500元，“我本来不要这钱，是孩子他舅说孩子还小，上学要用钱，我才拿了。”　　张福如称，上述判决后，他曾向汉中中院寄过“状子”，但无下文。具体时间，张福如称他已记不得了。　　他提供的由其署名、落款日期为2001年7月13日的“刑事附带民事状”显示，除了提出4.2万元经济赔偿外，张福如还提出要判处凶手死刑，“以牙还牙、以血还血”，并要求“对指示打死死者的王自新判处徒刑”。　　在这份“刑事附带民事状”中，张福如明确表示，17岁的王正军“是致死人命的凶手”。而在此次除夕血案发生后，张福如及其女儿表示，“打死汪秀萍的人是王正军的二哥王富军，因为王正军年龄小，不用判死刑所以才出来顶罪。”　　面对这一矛盾点，张福如表示，当初为什么这么写他记不清了，“我没文化，小学都没毕业，这个状子是花了50块钱找别人给我写的，写状子的人也已经死了。”　　前述村干部王明亮表示，汪秀萍被打伤后，村干部们怕凶手逃走，便去将王自新家围住，王自新还曾表示人是他打伤的，警察赶到后，将王自新、王正军父子均带走调查。王明亮分析：“王自新可能是想给儿子顶罪。但究竟是谁打的，司法查明了。”　　嫌犯素描张扣扣家门前拉起了警戒线。　　汪秀萍去世的时候，其子张扣扣年仅13岁。张扣扣的姐姐张丽波认为，母亲意外离世对张扣扣影响很大，“以前他都挺活泼的，从那事之后，他就变得内向了。”　　张福如、张丽波称，张丽波、张扣扣姐弟均目睹了那场导致汪秀萍死亡的冲突。　　张福如告诉澎湃新闻，张扣扣中学毕业之后便没有继续读书，而是跟随一个堂哥去新疆当了一段时间建筑工人。2001年12月，张扣扣应征入伍，成为一名武警战士，后于2003年12月退伍。　　2月20日，曾和张扣扣同年入伍，并在一个团服役的王旭（化名）告诉澎湃新闻，新兵连训练的时候，张扣扣告诉别人他参军的原因是要锻炼好身体报仇。“他这话被层层上报，全团开大会的时候政委在会上点名说过这个事情，我们大家才都知道了。”王旭说：“后来部队领导还对张扣扣进行了批评教育，扭转他这种想法。”　　张福如称，张扣扣退伍后，先后在广东、浙江打工。其中， 2004年至2007年张扣扣在深圳打工，四年未回家，只是每月寄钱回来，“总共寄回来16500元”。　　王旭称，他在2005年的时候也曾去深圳打工，“我是做巡防员，巡逻的时候遇到了在一家工厂做保安的战友张扣扣。他当时和一个离了婚的女人好着呢，住在一起。后来好像是因为家里反对，两个人就分手了。”　　之后，张扣扣又辗转至浙江杭州工作，2017年5月至8月还曾去阿根廷工作过一段时间。其朋友圈发布的年会信息显示，他所在的公司为一家上市公司。回国之后，张扣扣便一直在家呆着，直到事发。　　多位村民表示，张扣扣平常不太与人来往，也不像其他年轻人一样抽烟喝酒打牌。而令王旭印象深刻的是，有一年冬天下着雪，张扣扣穿着一件短袖骑摩托，“我问他不冷啊，他说不冷，我说你身体真好。”据王旭介绍，近些年战友们聚会，张扣扣也都没有参加过。虽然同住一村，但他最近一次见张扣扣，还是去年他给女儿办满月酒的时候。　　张福如告诉澎湃新闻，事发前他们父子二人相处的几个月里，张扣扣在家洗衣做饭打扫卫生，而他则早出晚归去做农活或者在附近打工。两人情感交流比较少，相互间也不怎么说话，“我不知道他都在想什么。他自尊心比较强，觉得干农活是没本事，丢人，但是收稻子的时候他会给我帮忙。”　　张扣扣的四伯张宏儒及几名村民分析称，之所以出这个事情，可能和张扣扣性格比较内向有关，“什么事情都藏在心里不讲”。此外，可能和他一直没有结婚也有关系，“有老婆和孩子了他考虑得就多，就不会做这种傻事。”　　至于没结婚的原因，张福如和部分村民认为，主要是家里经济条件不好。前述村民张辉也曾和张扣扣聊过这个话题，张扣扣自称在杭州打工的时候结交过一个女友，后来分手了，“后来别人给他介绍对象，他就说不要。”　　此外，张扣扣的大伯张忠儒等人认为，张扣扣母亲的事情，一直是他心里解不开的疙瘩。　　事发后，网上有传言称，张扣扣在杀人前曾前去祭拜母亲。但这一传言被张福如、张忠儒兄弟否认。澎湃新闻从多名村民处了解到，曾致张母汪秀萍死亡的王正军，出狱后常年在外，基本是过年祭祖扫墓才回来，且是当天回当天走。但是今年却有些反常，事发前王正军已在家住了七、八天。　　两年前的2016年2月22日，张扣扣曾在朋友圈转发过一篇关于杀人犯胡文海案的文章，其所配评论为“英雄，致敬”。而在张本人犯案后，一些网络文章也将其称为“英雄”。　　“杀人能是英雄？简直是胡说八道！”有村民表示不满。　　点击进入专题责任编辑：张建利';
> 
> var result = getUrls( post_content );
> 
> console.log( 'result:::', result );

**Comment by kevva** [comment]
Are there any valid URLs in there?

**Comment by sindresorhus** [comment]
He's probably referring to `www.thepaper.cn`, but it's missing the scheme part.

**Comment by kevva** [comment]
Doesn't need the scheme part if it has `www.` in the beginning. I just tested and it seems like the script literally doesn't finish because of some character in the string or something.

**Comment by EddieOne** [comment]
I was expecting href="" and href='' to work as well. no relative urls

**Comment by iTonyYo** [comment]
Modify the code [here](https://github.com/sindresorhus/get-urls/blob/master/index.js#L32) to:


```javascript
const urls = text.match(urlRegex({ strict: false })) || [];
```

That's it.

**Comment by betz** [comment]
i can confirm. I have a string containiing the url 'https://www.npmjs.com/package/get-urls' which it does not catch.

**Comment by betz** [comment]
this is my string:

"so i load this module https://www.npmjs.com/package/get-urls"

**Comment by betz** [comment]
when i remove the www. it works
