### ISSUE TITLE
Failed to minify code

### ISSUE THREAD

**Issue by studioraygun** [sindresorhus/get-urls#35]
I'm running a ReactJs build and get the following on running a build:

Failed to minify the code from this file:
/node_modules/get-urls/index.js:12

React ver 16.3.1. I'm also running get-urls-to-array:

`"get-urls": "^7.2.0",
    "get-urls-to-array": "^1.0.0",`

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
