### ISSUE TITLE
Additional URL pattern that are not detected by get-urls

### ISSUE THREAD

**Issue by mazen160** [sindresorhus/get-urls#40]
First of all, thank you for providing this excellent module. I have tested it, and the performance is great.

I found a way to bypass the detection on a form of urls.

`http:/github.com` is changed to `http://github.com` by browsers.

`data:text/html,<a href="http:/github.com/">Example</a>`

This can be marked as a "bypass" if the tool is used for security related functionality.

Quick fix:

This should not be the "right" fix, but it does allow get-urls to catch this pattern:

`text = text.replace(/(http|https)(\:\/) [^/|^"|^']  /ig, "http://")`

Which adds another `/` to urls. get-urls then normalize urls and catch the pattern.

**Comment by sindresorhus** [comment]
This module is definitely not meant for security purposes and I don't intend on adding support for hidden or invalid URLs. This module is simply meant to get all URLs in some text for informational or data purposes.
