### ISSUE TITLE
Error when ellipsis following URL

### ISSUE THREAD

**Issue by HugoGiraudel** [sindresorhus/get-urls#41]
Hey Sindre!

I get an error when having an ellipsis directly following a URL, like so:

```js
getUrls('Hey https://google.com…')
```

I assume this is not an intended behaviour?

**Comment by sindresorhus** [comment]
What error do you get?

**Comment by HugoGiraudel** [comment]
Pardon me, I should have started with that. :)

<img width="647" alt="screen shot 2018-10-25 at 9 31 01 am" src="https://user-images.githubusercontent.com/1889710/47483109-b8808a00-d838-11e8-94d7-2fba7e8262d8.png">

**Comment by sindresorhus** [comment]
This is most likely an issue with https://github.com/kevva/url-regex returning an invalid URL. It should preferably be fixed there to not pick up the `…`.

**Comment by HugoGiraudel** [comment]
Closing this then. Thanks Sindre. :)
