### ISSUE TITLE
IPv6 localhost/loopback Not Recognized

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/get-urls#43]
It seems that the IPv6 flavor of loopback address is not yet supported.

Test case:

```js
var getUrls = require("get-urls")
const text = ' http://[::]:55555';
getUrls(text); // <- Set {}, 0 Items
```

**Comment by sindresorhus** [comment]
See https://github.com/kevva/url-regex/issues/60

**Comment by shellscape** [comment]
👍 this can be closed in lieu of that issue if you'd like.
