### ISSUE TITLE
How extract the return Set values?

### ISSUE THREAD

**Issue by krishnaTORQUE** [sindresorhus/get-urls#49]
How extract the return Set values?
const getUrls = require('get-urls');
var links = getUrls(txt);

console.log(links);
/* Here I am getting
Set {}
Set {}
...
*/

console.log(links.Set);
OR
console.log(links[0]);

// getting undefined

**Comment by sindresorhus** [comment]
This is very basic JS:

```js
var links = [...getUrls(txt)];
console.log(links[0]);
```

**Comment by krishnaTORQUE** [comment]
Oops.
Thank you
