### ISSUE TITLE
Doesn't work on React Native

### ISSUE THREAD

**Issue by smakosh** [sindresorhus/get-urls#50]
Doesn't seem to work with React Native 0.60.5

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not React Native. It's up to you to transpile it with Babel if you want to use it there.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by infostreams** [comment]
You can use [Anchorme](http://alexcorvi.github.io/anchorme.js/#listing) which *does* support React Native out of the box.
