### ISSUE TITLE
Invalid URL: WWW.POS.COM

### ISSUE THREAD

**Issue by ganuonglachanh** [sindresorhus/get-urls#53]
```
let url = 'WWW.POS.COM';
let test = getUrls(url,{extractFromQueryString: true});
```
getUrls failed with this error:
`Invalid URL: WWW.POS.COM`

in line 8:

`
const {searchParams} = (new URL(url.replace(/^(\/\/|(www\.))/, 'http://$2')));
`

solution:
add **i** in regex

`
const {searchParams} = (new URL(url.replace(/^(\/\/|(www\.))/i, 'http://$2')));
`

**Comment by sindresorhus** [comment]
PR welcome with a test.
