### ISSUE TITLE
[Vulnerability] Passing a long string to the url-regex library is resulting in 100% CPU usage

### ISSUE THREAD

**Issue by fx2000** [sindresorhus/get-urls#59]
No way out but a SIGINT, you can read more about it [here](https://github.com/kevva/url-regex/issues/70) and [here](https://snyk.io/test/npm/get-urls/9.2.0). I can confirm ```get-urls``` is affected.

**Comment by justinlazaro-iselect** [comment]
hopefully, there's an update about on this

**Comment by niftylettuce** [comment]
I'm the original author that found this vulnerability, and have released https://github.com/niftylettuce/url-regex-safe as the fix.

**Comment by fx2000** [comment]
> I'm the original author that found this vulnerability, and have released https://github.com/niftylettuce/url-regex-safe as the fix.

Excellent. I replaced "url-regex" with "url-regex-safe" and create a [PR](https://github.com/sindresorhus/get-urls/pull/61) for this change.

**Comment by niftylettuce** [comment]
@fx2000 @sindresorhus The url-regex-safe version needs updated to v1.0.2
