### ISSUE TITLE
Markdown parsing

### ISSUE THREAD

**Issue by wayneashleyberry** [sindresorhus/get-urls#6]
Extracting url's from within Markdown links doesn't work :(

```sh
❯ echo 'This is a [test](http://www.google.com).' | get-urls
```

**Comment by sindresorhus** [comment]
@kevva Might be useful if [`url-regex`](https://github.com/kevva/url-regex) supported this?

**Comment by kevva** [comment]
Yup.

**Comment by sindresorhus** [comment]
Moved to https://github.com/kevva/url-regex/issues/13

**Comment by wayneashleyberry** [comment]
Thanks @sindresorhus
