### ISSUE TITLE
Invalid regular expression: invalid group specifier name in React / Safari

### ISSUE THREAD

**Issue by gbourne1** [sindresorhus/get-urls#65]
In a compiled React build, a "Invalid regular expression: invalid group specifier name" error occurs in Safari preventing the app from loading. Perhaps a new regular expression was added in version 10?

Validated version 9.2.1 is ok and only breaks with version 10

StackOverflow discussion of the possible issue: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by sindresorhus** [comment]
Stay on version 9 if you need Safari support. This package mainly targets Node.js. It's up to you to transpile with Babel for browser support.
