### ISSUE TITLE
get-urls interaction with Chrome Developer Tools in Electron app

### ISSUE THREAD

**Issue by Dotnaught** [sindresorhus/get-urls#66]
Node 12.16.3
Chrome 85.0.4183.102
nvm 0.35.3
macOS 10.15.6
Electron 10.1.1
npm 6.14.8

I've been using get-urls in the refactoring of an Electron-based RSS app and recently updated to Electron 10.1.1 and updated all the various dependences/modules. After that, launching the app causes Chrome dev tools in the app to crash. After trying to hunt down the source of the problem, it appears to have something to do with get-urls – I can get the app to perform as expected by commenting out the get-urls require statement. 

I'm not sure what the specific issue might be since there's no error information output in my terminal and the dev tools console is inaccessible. Any thoughts on steps to take to diagnose the issue more specifically?

**Comment by sindresorhus** [comment]
This is not really the place to ask for such support. This package is working perfectly in Node.js. Any other usage and you're on your own, unfortunately.
