### ISSUE TITLE
False possitive

### ISSUE THREAD

**Issue by Goles** [sindresorhus/get-urls#69]
I can see that the following string `hola.chao` is returning `http://hola.ch` using *get-urls*. This is not something I would expect since there's no space between `ch` and `ao` (for `chao` that is).

**Comment by sindresorhus** [comment]
This is unfortunately a known limitation in the package we use for extracting URLs: https://github.com/niftylettuce/url-regex-safe#limitations

**Comment by Goles** [comment]
I understand, feel free to close my issue.
