### ISSUE TITLE
Semicolons as URL separator break URLs

### ISSUE THREAD

**Issue by Namchee** [sindresorhus/get-urls#71]
## Overview

It seems that separators such as semicolons are being included in the result.

For example: `http://www.xxx.com/;http://www.yyy.com/` will produce `['http://www.xxx.com/;', 'http://www.yyy.com/']`

However, accessing `http://www.xxx.com/;` directly will lead to 404, which is unintended as semicolons are just separators in this context.

**Comment by sindresorhus** [comment]
This needs to be reported to https://github.com/niftylettuce/url-regex-safe, which is what we use to detect the URL. We cannot just remove the `;` here as `http://www.xxx.com/;` is technically [a valid URL](https://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid).

**Comment by Namchee** [comment]
Thank you for your response.

I'll temporarily close this issue and continue there. Will re-open later.
