### ISSUE TITLE
Does not return www

### ISSUE THREAD

**Issue by krishnaTORQUE** [sindresorhus/get-urls#75]
Content: "Test Youtube https://www.youtube.com/watch?v=Nk9877d2rJw"

Returns ["https://youtube.com/watch?v=Nk9877d2rJw"]

Suppose to return ["https://www.youtube.com/watch?v=Nk9877d2rJw"]

Why its excluding `www` ?
Even when `requireSchemeOrWww` flag is true

**Comment by sindresorhus** [comment]
> Even when requireSchemeOrWww flag is true

That option is about detection, not normalization.

**Comment by sindresorhus** [comment]
It makes no difference whether the `www.` is there or not in most cases. If you insist, you can change the behavior with the options: https://github.com/sindresorhus/get-urls#options (See the linked normalize-url options docs)
