### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by andersaamodt** [sindresorhus/get-urls#82]
I am making a TypeScript server, compiling using `tsc`, and I get this error when I try to `import getUrls from 'get-urls'`:

`Error [ERR_REQUIRE_ESM]: require() of ES Module <project root>/node_modules/get-urls/index.js from <project root>/dist/src/server/spec.js not supported.
Instead change the require of index.js in <project-root>/dist/src/server/spec.js to a dynamic import() which is available in all CommonJS modules.`

This is the only package in my project giving me this error so I guess I will just temporarily disable it or replace it with the regex package that this project includes.

Since this is the only package giving me this error, I am guessing it is something in the way the package module is set up that is giving me this error?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
